### PR TITLE
feat: speed up point-object assignment with a bounding volume hierarchy

### PR DESCRIPTION
**Pull request by haakonflatval-cognite**
# Description

## Note: This PR is superseded by #2327 and will likely be deleted.

Speeds up the point-object matching process by using a Bounding Volume Hierarchy (BVH). It improves the loading/ point-object matching time for the root sector of the point cloud from ~35s to 1-2s.

Further suggestions for performance improvements are given in [a JIRA issue](https://cognitedata.atlassian.net/browse/REV-437).

This PR also fixes an issue where box matrices from the backend where not interpreted in row-major order as they should.

This PR currently targets the branch for workers in libraries, which it depends on. It should eventually target and be merged into the point cloud feature branch.

Further work: Tests

# Checklist:

Here is a checklist that should completed before merging this given feature. 
Any shortcomings from the items below should be explained and detailed within the contents of this PR.

- [x] I am proud of this feature.
- [ ] I have performed a self-review of my own code.
- [x] I have manually tested this for different scenarios (different models, formats, devices, browsers).
- [x] I have commented my code in hard-to-understand areas.
- [x] I have made corresponding changes to the public documentation.
- [ ] I have added unit and visuals tests to prove that my feature works to the best of my ability.
- [x] I have refactored the code for readability to the best of my ability.
- [x] I have checked that my changes do not introduce regressions in the public documentation.
- [x] I have outlined any known defects / lacking capabilities in the contents of this PR.
- [x] I have listed any remaining work that should follow this PR in the description or jira/miro/etc.
- [x] I have added TSDoc to any public facing changes.
- [x] I have added "developer documentation" in any package README.md that is related / applicable to this PR.
- [x] I have noted down and am currently tracking any technical debt introduced in this PR.
- [x] I have thoroughly thought about the architecture of this implementation.
- [x] I have asked peers to test this feature.

### CODE REVIEW

**Comment by larsmoa** [comment]
Change description of PR to describe what we achieve (it's currently how ;) )

**Comment by haakonflatval-cognite** [comment]
We have arrived at the conclusion that we want this merged into the feature branch now. It is not as good as we would want, but it provides an enormous improvement over the previous approach.

That being said, there is quite a bit of garbage lying around. The BVH implementation is unused and the octree is tested. A lot of superfluous out-commented lines are still in `assignObjects.ts` for remembrance. The cleanup work is being tracked in https://cognitedata.atlassian.net/browse/REV-374

**Comment by haakonflatval-cognite** [comment]
Just to make it clear here, this PR is intended to be superseded by #2327 , and will be closed as soon that one is merged.

**Comment by haakonflatval-cognite** [comment]
Closing, as it is superseded by #2327

**Pull request closed without merging**
