### PR TITLE
fix: dragable clipping plane example being broken by new threejs version

### PR DESCRIPTION
**Pull request by Savokr**
Fixed docs example of draggable clipping plane

### CODE REVIEW

**Comment by christjt** [comment]
*BIP* *BOP* I am a bot. Here is your preview-doc: https://cognitedata.github.io/reveal-docs-preview/1637/docs/next/

**Comment by Savokr** [comment]
> _BIP_ _BOP_ I am a bot. Here is your preview-doc: https://cognitedata.github.io/reveal-docs-preview/1637/docs/next/

Isn't it a master documentation? I mean we need to merge it first to see it there, right?

**Comment by larsmoa** [comment]
You've changed Version 2.0 docs - reset changes you have in ` documentation/versioned_docs/version-2.x` and move this to clipping.tsx under `documentation/docs/`.

Note that `documentation/versioned_docs` (almost) only should be changed we release when the versioned docs are replaced using an automated procedure.

**Comment by christjt** [comment]
LGTM! @larsmoa Do you know if we have to do anything for the doc here to propagate to version 2.x, or will this happen automagically on deploy?

**Comment by larsmoa** [comment]
> LGTM! @larsmoa Do you know if we have to do anything for the doc here to propagate to version 2.x, or will this happen automagically on deploy / release?

The docs are replaced using the `replace-2.x` script in documentation/package.json. 

We need to streamline this more though....

**Review by christjt — APPROVED** [review]

**Pull request merged**
