### PR TITLE
fix: threejs version mismatch in examples & viewer @types

### PR DESCRIPTION
**Pull request by pramodcog**

### CODE REVIEW

**Review by haakonflatval-cognite — APPROVED** [review]
LGTM :+1:

**Review by christjt — CHANGES_REQUESTED** [review]
Please bump all the way to 0.138.3 as 0.138.0 has a bug which causes rendering issues.

**Comment by christjt** [comment]
We also need to update the viewer to 138.3

**Comment by pramodcog** [comment]
Closing this as we have other [PR ](https://github.com/cognitedata/reveal/pull/1986) for version upgrade 138.3

**Pull request closed without merging**
