### PR TITLE
add eslint-plugin-jsdoc

### PR DESCRIPTION
**Pull request by maksnester**
I personally already hate it. But hopefully, you will find it useful 😅

### CODE REVIEW

**Review by larsmoa — COMMENTED** [review]
Should we always enforce `@param` and `@return`?

**Comment by maksnester** [comment]
> Should we always enforce @param and @return?

Param - yes, it's enforced. Return is optional. Because you don't have to specify type for return and description is often redundant becaus it's obvious from return type and function name. That's why I don't want to enforce it. But I can, if you think it makes sense.

**Comment by larsmoa** [comment]
Regarding param I'm fine with enforcing it, but sometimes I feel doc is a bit redundant, e.g. doc for treeIndex

**Review by larsmoa — APPROVED** [review]

**Comment by maksnester** [comment]
> Regarding param I'm fine with enforcing it, but sometimes I feel doc is a bit redundant, e.g. doc for treeIndex

I agree. It's really hard to find some balance here in requiring things and keeping configuration not stupidly annoying.

**Pull request merged**
