### PR TITLE
feat: upgrade to Webpack 5

### PR DESCRIPTION
**Pull request by haakonflatval-cognite**
# Description

Please include a summary of the change and which issue is fixed. 
Please also include relevant motivation and context. 
List any dependencies that are required for this change.

# Checklist:

Here is a checklist that should completed before merging this given feature. 
Any shortcomings from the items below should be explained and detailed within the contents of this PR.

- [ ] I am proud of this feature.
- [ ] I have performed a self-review of my own code.
- [ ] I have manually tested this for different scenarios (different models, formats, devices, browsers).
- [ ] I have commented my code in hard-to-understand areas.
- [ ] I have made corresponding changes to the public documentation.
- [ ] I have added unit and visuals tests to prove that my feature works to the best of my ability.
- [ ] I have refactored the code for readability to the best of my ability.
- [ ] I have checked that my changes do not introduce regressions in the public documentation.
- [ ] I have outlined any known defects / lacking cabilities in the contents of this PR.
- [ ] I have listed any remaining work that should follow this PR in the description or jira/miro/etc.
- [ ] I have added TSDoc to any public facing changes.
- [ ] I have added "developer documentation" in any package README.md that is related / applicable to this PR.
- [ ] I have noted down and am currently tracking any technical debt introduced in this PR.
- [ ] I have thoroughly thought about the architecture of this implementation.
- [ ] I have asked peers to test this feature.

### CODE REVIEW

**Comment by haakonflatval-cognite** [comment]
Note: the visual tests seem to fail because the rendering engine specified in the puppeteer configuration is not available in the CI workers. It seems to fall back to the default ('--use-gl=egl`).

**Comment by haakonflatval-cognite** [comment]
Current status:  The viewer and the examples seem to work fine with Webpack 5 now. The documentation is still not running properly. On my end it fails with the errors `__webpack_modules__[moduleId] is not a function` and `Uncaught ReferenceError: process is not defined`. 

The latest commit at the point of this comment is an attempt at converting `three` to a peer dependency (which would break the API, but can postpone release to 4.x). It is only provided for convenience if that path seems more feasible. The previous commit (https://github.com/cognitedata/reveal/pull/2230/commits/2b75e9beca0c416b43242b2446cfe8bd285f82fc) preserves the behavior of today's bundling (it doesn't bundle Three JS, but it will usually be installed by the client anyway). Both of these commits shows the same error in the browser when using the documentation.

**Comment by christjt** [comment]
> Current status: The viewer and the examples seem to work fine with Webpack 5 now. The documentation is still not running properly. On my end it fails with the errors `__webpack_modules__[moduleId] is not a function` and `Uncaught ReferenceError: process is not defined`.
> 
> The latest commit at the point of this comment is an attempt at converting `three` to a peer dependency (which would break the API, but can postpone release to 4.x). It is only provided for convenience if that path seems more feasible. The previous commit ([2b75e9b](https://github.com/cognitedata/reveal/commit/2b75e9beca0c416b43242b2446cfe8bd285f82fc)) preserves the behavior of today's bundling (it doesn't bundle Three JS, but it will usually be installed by the client anyway). Both of these commits shows the same error in the browser when using the documentation.

Process not defined is something a have been expecting. Basically Webpack 5 does not polyfill Nodejs things (which process is). The "is not a function" thing I am not quite sure of though :(

**Comment by christjt** [comment]
Also this thread still scares me: https://github.com/webpack/webpack/issues/11277, and was the original reason I gave up porting to webpack 5

**Comment by christjt** [comment]
Closing this as it has been merged, well done!

**Pull request closed without merging**
