### PR TITLE
feat: 360 image annotation visibility toggle

### PR DESCRIPTION
**Pull request by haakonflatval-cognite**
#### Type of change

Feat  

#### Jira ticket :blue_book:

https://cognitedata.atlassian.net/browse/REV-875

## Description :pencil:

Toggle to turn on and off annotation visibility.

## How has this been tested? :mag:

- Open Reveal examples locally
- Go to https://localhost:3000/?project=3d-test&env=greenfield-3d&modelId=4923307033982497&revisionId=3100284276970593
- Load 360 images `helideck-site-2-jpeg`
- The lowermost 360 entity has annotations
- Click the toggle in the 360 UI to hide/show annotations
- Make sure annotations are toggled even when not loaded and/or not visible

## Checklist :ballot_box_with_check:

- [x] I am proud of this feature.
- [x] I have performed a self-review of my own code.
- [x] I have added PR type (Feat, Bug, Chore, Test, Docs, Style, Refactor) to the PR title.
- [ ] I have manually tested this for different scenarios (different models, formats, devices, browsers).
- [ ] I have commented my code in hard-to-understand areas.
- [ ] I have made corresponding changes to the public documentation.
- [ ] I have added unit and visuals tests to prove that my feature works to the best of my ability.
- [ ] I have refactored the code for readability to the best of my ability.
- [ ] I have checked that my changes do not introduce regressions in the public documentation.
- [ ] I have outlined any known defects / lacking capabilities in the contents of this PR.
- [ ] I have listed any remaining work that should follow this PR in the description or jira/miro/etc.
- [ ] I have added TSDoc to any public facing changes.
- [ ] I have added "developer documentation" in any package README.md that is related / applicable to this PR.
- [ ] I have noted down and am currently tracking any technical debt introduced in this PR.
- [ ] I have thoroughly thought about the architecture of this implementation.
- [x] I have asked peers to test this feature.

### CODE REVIEW

**Review by Savokr — APPROVED** [review]
Looks good! One minor thing I noticed is that annotations are often loaded before the actual 360 image cubemap is created, so this creates a strange effect of floating meshes before you enter a 360 image, I guess we should ensure that 360 image cubemap is added to the scene first and then annotations should be added as well. I think it could be addressed in a separate PR as it is not critical. Video with this behaviour: 

https://user-images.githubusercontent.com/45129444/234256897-caccf1f6-bd98-41b6-85a1-9fecf0c1d380.mov

**Comment by haakonflatval-cognite** [comment]
> Looks good! One minor thing I noticed is that annotations are often loaded before the actual 360 image cubemap is created
Yes, I have seen this. It's tracked in https://cognitedata.atlassian.net/browse/REV-882

**Comment by haakonflatval-cognite** [comment]
I have started to wonder whether this should just be set using the styling API. `collection.setDefaultStyle({ visibility: false });` does the same thing as `collection.setImageAnnotationVisibility(false);`.

**Comment by haakonflatval-cognite** [comment]
I've decided to butcher this in favor of the styling PR :( Oh well, maybe we'll see use for it in the future

**Pull request closed without merging**
