### PR TITLE
fix: share() so `consumedSectorObservable` works

### PR DESCRIPTION
**Pull request by hayer**
Currently using the `Observable<ConsumedSector>` from `CadModelUpdateHandler` seems to make it _not work_ .. in lack of better description. The reason seems to be that it is not shared properly.

Proposing this as a fix.

### CODE REVIEW

**Comment by christjt** [comment]
Hey, what exactly doesn't work? When getting the consumed sector observable, we do share it.

```
  consumedSectorObservable(): Observable<ConsumedSector> {
    return this._updateObservable.pipe(share());
  }
```

**Comment by j-bjorne** [comment]
How are you accessing this Observable?

With the method

```
  consumedSectorObservable(): Observable<ConsumedSector> {
    return this._updateObservable.pipe(share());
  }
```

it shares this pipe the way you propose it. Do you have any code or snippet of yours to see why exactly it fails?

**Comment by hayer** [comment]
```
        const revealManager = (<any>global3DViewer).revealManager;
        const cadManager = revealManager._cadManager;
        const cadModelUpdateHandler = cadManager._cadModelUpdateHandler as CadModelUpdateHandler;

        const consumedSectorObservable = cadModelUpdateHandler.consumedSectorObservable().subscribe(console.log);
```

Using `consumedSectorObservable()` without this change seems to make loading hang..?

**Comment by christjt** [comment]
We don't see the need for this change and cannot reproduce the example. If you subscribe to the observer, then it seems to pass data just fine. Please let me know of the case you are trying to solve if this is a blocker.

**Pull request closed without merging**
