### PR TITLE
fix: Update Cognite3DViewer: Fixes issue where cameraManager in options wa…

### PR DESCRIPTION
**Pull request by kjerstifagerholt**
…s not used

#### Type of change

Bug 

#### Jira ticket :blue_book:

https://cognitedata.atlassian.net/browse/

## Description :pencil:

Missing parentheses lead to wrong output for initialActiveCameraManager.

## Checklist :ballot_box_with_check:

- [ ] I am proud of this feature.
- [ ] I have performed a self-review of my own code.
- [ ] I have added PR type (Feat, Bug, Chore, Test, Docs, Style, Refactor) to the PR title.
- [ ] I have manually tested this for different scenarios (different models, formats, devices, browsers).
- [ ] I have commented my code in hard-to-understand areas.
- [ ] I have made corresponding changes to the public documentation.
- [ ] I have added unit and visuals tests to prove that my feature works to the best of my ability.
- [ ] I have refactored the code for readability to the best of my ability.
- [ ] I have checked that my changes do not introduce regressions in the public documentation.
- [ ] I have outlined any known defects / lacking capabilities in the contents of this PR.
- [ ] I have listed any remaining work that should follow this PR in the description or jira/miro/etc.
- [ ] I have added TSDoc to any public facing changes.
- [ ] I have added "developer documentation" in any package README.md that is related / applicable to this PR.
- [ ] I have noted down and am currently tracking any technical debt introduced in this PR.
- [ ] I have thoroughly thought about the architecture of this implementation.
- [ ] I have asked peers to test this feature.

### CODE REVIEW

**Review by nilscognite — APPROVED** [review]
LGTM

**Comment by kjerstifagerholt** [comment]
> Hi, @kjerstifagerholt , there seems to be a lint error in CI. You can fix it by running `yarn lint --fix` in the `viewer` folder. Let us know if you want us to fix all the CI checks for you and merge this PR 👍

@haakonflatval-cognite  Ok sorry about that. I currently don't have access to the repo on my computer so it would be great if you can help out and fix the checks and merge it 👍 Thanks!

**Comment by haakonflatval-cognite** [comment]
> > Hi, @kjerstifagerholt , there seems to be a lint error in CI. You can fix it by running `yarn lint --fix` in the `viewer` folder. Let us know if you want us to fix all the CI checks for you and merge this PR 👍
> 
> @haakonflatval-cognite Ok sorry about that. I currently don't have access to the repo on my computer so it would be great if you can help out and fix the checks and merge it 👍 Thanks!

No worries - we'll fix and merge it :+1:

**Comment by haakonflatval-cognite** [comment]
@kjerstifagerholt We have now released this patch as part of Reveal version 4.10.2

**Pull request merged**
